openapi: 3.0.0
info:
  description: This is a Mobile Orders API
  version: 1.0.0-oas3
  title: Mobile Device Orders
paths:
  /orders/phone:
    post:
      summary: orders a mobile phone
      operationId: app.order_mobile_phone
      description: Receives a mobile phone order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MobilePhoneOrder'
        description: Mobile Phone Order
      responses:
        '201':
          description: order added
        '400':
          description: 'invalid input, object invalid'
  /orders/tablet:
    post:
      summary: orders a tablet
      operationId: app.order_tablet
      description: Receives atablet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TabletOrder'
        description: Tablet Order
      responses:
        '201':
          description: order added
        '400':
          description: 'invalid input, object invalid'
  /orders/stats:
    get:
      summary: Gets order stats for phones and tablets
      operationId: app.get_order_stats
      description: Gets order stats
      responses:
        '200':
          description: current order stats
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderStats'
        '400':
          description: stats do not exist
components:
  schemas:
    MobilePhoneOrder:
      type: object
      required:
        - customer_id
        - make
        - model
        - price
        - timestamp
      properties:
        customer_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        make:
          type: string
          example: Apple
        model:
          type: string
          example: iPhone 8S
        price:
          type: number
          example: 799.98
        timestamp:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
    TabletOrder:
      type: object
      required:
        - customer_id
        - make
        - model
        - price
        - timestamp
      properties:
        customer_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        make:
          type: string
          example: Apple
        model:
          type: string
          example: iPad Air
        price:
          type: number
          example: 599.98
        timestamp:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
    OrderStats:
      required:
        - num_phones
        - num_tablets
      properties:
        num_phones:
          type: integer
          example: 1000
        num_tablets:
          type: integer
          example: 2000
